### ISSUE TITLE
log in error raised 

### ISSUE THREAD

**Issue by delphieritas** [nusdbsystem/singa-auto#106]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "singa-auto/singa_auto/client/client.py", line 101, in login
    'password': password
  File "singa-auto/singa_auto/client/client.py", line 792, in _post
    return self._parse_response(res)
  File "singa-auto/singa_auto/client/client.py", line 837, in _parse_response
    raise SingaAutoConnectionError(res.text)
singa_auto.client.client.SingaAutoConnectionError
...
 FATAL:  remaining connection slots are reserved for non-replication superuser connections\n\n(Background on this error at: http://sqlalche.me/e/e3q8)\n","error_code":500,"message":"System Internal Error","success":1

**Comment by naili-xing** [comment]
fixed in https://github.com/nusdbsystem/singa-auto/pull/107
