### ISSUE TITLE
Error while creating inference job

### ISSUE THREAD

**Issue by airlovelq** [nusdbsystem/singa-auto#67]
The Error happens after I finished a train job using TfFeedFoward model and fashion mnist dataset. And the train job was Success. The client response is as below:

Traceback (most recent call last):
  File "/root/singa_auto/admin/services_manager.py", line 97, in create_inference_services
    inferenceAppName=inferenceAppName)
  File "/root/singa_auto/admin/services_manager.py", line 397, in _create_predictor
    inferenceAppName=inferenceAppName
  File "/root/singa_auto/admin/services_manager.py", line 569, in _create_service
    raise e
  File "/root/singa_auto/admin/services_manager.py", line 557, in _create_service
    ingress_body=json.loads(ingress_info.ingress_body)
  File "/root/singa_auto/container/kubernetes_operation.py", line 92, in update_ingress
    body=body)
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/kubernetes/client/apis/networking_v1beta1_api.py", line 1339, in replace_namespaced_ingress_with_http_info
    collection_formats=collection_formats)
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 334, in call_api
    _return_http_data_only, collection_formats, _preload_content, _request_timeout)
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 168, in __call_api
    _request_timeout=_request_timeout)
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/kubernetes/client/api_client.py", line 385, in request
    body=body)
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/kubernetes/client/rest.py", line 276, in PUT
    body=body)
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/kubernetes/client/rest.py", line 222, in request
    raise ApiException(http_resp=r)
kubernetes.client.rest.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 25 May 2020 03:05:05 GMT', 'Content-Length': '258'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ingresses.networking.k8s.io \"ingress-predictor\" not found","reason":"NotFound","details":{"name":"ingress-predictor","group":"networking.k8s.io","kind":"ingresses"},"code":404}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/singa_auto/utils/auth.py", line 80, in wrapped
    return f(auth, *args, **kwargs)
  File "/root/singa_auto/utils/requests_params.py", line 65, in wrapped
    return f(params=combined_params, *args, **kwargs)
  File "/root/singa_auto/admin/view/inference_job.py", line 47, in create_inference_job
    description=params.get('description', None)
  File "/root/singa_auto/admin/admin.py", line 708, in create_inference_job
    inference_job_id=inference_job.id,
  File "/root/singa_auto/admin/services_manager.py", line 121, in create_inference_services
    raise ServiceDeploymentError(e)
singa_auto.admin.services_manager.ServiceDeploymentError: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'Date': 'Mon, 25 May 2020 03:05:05 GMT', 'Content-Length': '258'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"ingresses.networking.k8s.io \"ingress-predictor\" not found","reason":"NotFound","details":{"name":"ingress-predictor","group":"networking.k8s.io","kind":"ingresses"},"code":404}

  File "/home/luqin/singa-auto/singa_auto/client/client.py", line 828, in _parse_response
    raise SingaAutoConnectionError(res.text)
  File "/home/luqin/singa-auto/singa_auto/client/client.py", line 783, in _post
    return self._parse_response(res)
  File "/home/luqin/singa-auto/singa_auto/client/client.py", line 646, in create_inference_job
    'description': description
  File "/home/luqin/singa-auto/test_multi_model.py", line 15, in <module>
    cli.create_inference_job('test13',budget={'GPU_COUNT':0}, description='test')

It seems like raising exception when calling k8s ingress api. I don't know how to fix it, because I have never done research on the k8s ingress tech.

**Comment by naili-xing** [comment]
are u running those on your cluster? i think it is fixed now, please refer to pull request #68

**Comment by airlovelq** [comment]
> are u running those on your cluster? i think it is fixed now, please refer to pull request #68

I try the newest code, but another error happened. It seems like param error in calling "create_namespaced_ingress" api. The log is as below:

Traceback (most recent call last):
  File "/root/singa_auto/admin/services_manager.py", line 97, in create_inference_services
    inferenceAppName=inferenceAppName)
  File "/root/singa_auto/admin/services_manager.py", line 397, in _create_predictor
    inferenceAppName=inferenceAppName
  File "/root/singa_auto/admin/services_manager.py", line 569, in _create_service
    raise e
  File "/root/singa_auto/admin/services_manager.py", line 557, in _create_service
    ingress_body=json.loads(ingress_info.ingress_body)
  File "/root/singa_auto/container/kubernetes_operation.py", line 114, in update_ingress
    body=body)
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/kubernetes/client/apis/networking_v1beta1_api.py", line 93, in create_namespaced_ingress_with_http_info
    " to method create_namespaced_ingress" % key
TypeError: Got an unexpected keyword argument 'name' to method create_namespaced_ingress

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/envs/singa_auto/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/singa_auto/utils/auth.py", line 80, in wrapped
    return f(auth, *args, **kwargs)
  File "/root/singa_auto/utils/requests_params.py", line 65, in wrapped
    return f(params=combined_params, *args, **kwargs)
  File "/root/singa_auto/admin/view/inference_job.py", line 47, in create_inference_job
    description=params.get('description', None)
  File "/root/singa_auto/admin/admin.py", line 708, in create_inference_job
    inference_job_id=inference_job.id,
  File "/root/singa_auto/admin/services_manager.py", line 121, in create_inference_services
    raise ServiceDeploymentError(e)
singa_auto.admin.services_manager.ServiceDeploymentError: Got an unexpected keyword argument 'name' to method create_namespaced_ingress
  File "/home/luqin/singa-auto/singa_auto/client/client.py", line 828, in _parse_response
    raise SingaAutoConnectionError(res.text)
  File "/home/luqin/singa-auto/singa_auto/client/client.py", line 783, in _post
    return self._parse_response(res)
  File "/home/luqin/singa-auto/singa_auto/client/client.py", line 646, in create_inference_job
    'description': description
  File "/home/luqin/singa-auto/test_multi_model.py", line 15, in <module>
    res = cli.create_inference_job('test15',budget={'GPU_COUNT':0}, description='test')

**Comment by airlovelq** [comment]
I think I have fixed it now. "create_namespaced_ingress_with_http_info" api does not need name argument.

**Comment by naili-xing** [comment]
> I think I have fixed it now. "create_namespaced_ingress_with_http_info" api does not need name argument.

please refer to pr #69 , it's fixed in this pr,
