### ISSUE TITLE
Train error

### ISSUE THREAD

**Issue by airlovelq** [nusdbsystem/singa-auto#90]
I found an error while training. The log is as below:

03-Jul-20 07:53:42 singa_auto.worker.train INFO Marking trial as running in store...
03-Jul-20 07:53:42 singa_auto.worker.train INFO Creating model instance...
03-Jul-20 07:53:42 singa_auto.worker.train ERROR Error while running trial:
03-Jul-20 07:53:42 singa_auto.worker.train ERROR Traceback (most recent call last):
  File "/root/singa_auto/worker/train.py", line 135, in _perform_trial
    model_inst = self._load_model(proposal)
  File "/root/singa_auto/worker/train.py", line 107, in wrapped
    raise e
  File "/root/singa_auto/worker/train.py", line 100, in wrapped
    result = f(self, *args, **kwargs)
  File "/root/singa_auto/worker/train.py", line 190, in _load_model
    model_inst = py_model_class(**proposal.knobs)
  File "/root/LightGBM-8f6409b0-c459-4b96-8344-f965c92408c1.py", line 38, in __init__
TypeError: object.__init__() takes no parameters

**Comment by nudles** [comment]
@naili-xing is this error resolved?

**Comment by naili-xing** [comment]
Yes, in pr https://github.com/nusdbsystem/singa-auto/pull/93
